---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
- name: config-server-release
- name: bosh-cli
- name: config-server

outputs:
- name: bosh-release

run:
  path: config-server-release/ci/tasks/bosh-release.sh
