---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
- name: config-server-release
- name: bosh-cli

outputs:
- name: config-server-repo

run:
  path: config-server-release/ci/tasks/bump-submodule.sh
